### ISSUE TITLE
Android Wear compatibility 

### ISSUE THREAD

**Issue by nathanbegin** [michaelkourlas/voipms-sms-client#103] opened 2017-01-02 22:26 UTC
It might be nice to review the compatibility of the app with Android Wear.. because I am not able to answer my sms from my Android Wear smartwatch since I use voip.ms for talk and text with a data plan.

Nathan

**Comment by michaelkourlas** [comment] 2017-01-02 22:29
Duplicate of https://github.com/michaelkourlas/voipms-sms-client/issues/34.

**Closed by michaelkourlas** 2017-01-02 22:29 UTC

**Comment by nathanbegin** [comment] 2017-01-02 22:33
Ok I see that its a duplicate ticket but the problem isn't fix yet  ???

**Comment by michaelkourlas** [comment] 2017-01-06 19:36
No, I haven't added support for Android Wear yet.

**Comment by nathanbegin** [comment] 2017-01-06 21:53
Oh I see, do you plan to add this feature soon?

**Comment by michaelkourlas** [comment] 2017-01-07 00:40
It's not a top priority, unfortunately - maybe in release v0.4.8.

**Comment by nathanbegin** [comment] 2017-01-07 00:49
It would be very nice for the Android Wear smartwatch users :)

By the way, the app is great ;)
