### ISSUE TITLE
Sync failed: corrupt response

### ISSUE THREAD

**Issue by zlehnherr1** [michaelkourlas/voipms-sms-client#274] opened 2024-06-07 16:09 UTC
Title is the error I get, I believe that I saw a reddit post about VoIP.ms changing something with their api.

**Comment by auralius-dev** [comment] 2024-06-07 22:11
I get this error too, when waiting to receive messages. I can send them just fine. First time user of this application, since five minutes ago.

**Comment by michaelkourlas** [comment] 2024-06-07 23:15
Duplicate of https://github.com/michaelkourlas/voipms-sms-client/issues/273 - please see that issue for a workaround.

**Closed by michaelkourlas** 2024-06-07 23:15 UTC
