### ISSUE TITLE
Ability to block numbers

### ISSUE THREAD

**Issue by kirkawolff** [michaelkourlas/voipms-sms-client#271] opened 2024-04-16 16:54 UTC
Voip.ms has the notion of phone lists. It would be nice to be able to long-press on a sms chat and add it to a blocklist

**Comment by michaelkourlas** [comment] 2024-05-20 23:22
Duplicate of https://github.com/michaelkourlas/voipms-sms-client/issues/119.

**Closed by michaelkourlas** 2024-05-20 23:22 UTC
