### ISSUE TITLE
Slow Response When Sending Message

### ISSUE THREAD

**Issue by RithHugDo** [michaelkourlas/voipms-sms-client#227] opened 2021-02-24 21:40 UTC
Since the 0.6.14 update I wanted to chime in on something I've noticed. I saw one of the recent Google play reviews about SMS not getting sent and part of the message being kept as a draft. I've had the same behavior since the update to 0.6.14 and it seems to happen if you hit send from the app and then navigate away from the conversation.

It's taking a long time for the sent message to show in the conversation (several seconds) from when you hit send until it shows up. I can't remember but it seems like it used to post to the conversation immediately but then it might take several seconds to actually send?

**Comment by impactav-paul** [comment] 2021-02-24 22:22
Seeing similar behaviour here on Android 11/Pixel 3 XL with 0.6.14. I had a couple of messages take minutes though, not seconds, to send and appear properly in the conversation.

Navigating away from the conversation, I could see part of the first message appear as a draft in the contact/conversation list. After some time this seemed to repeat for the second message I had sent as well. Perhaps sending two messages in quick succession was enough to really exacerbate whatever the underlying issue is.

**Comment by xenophane** [comment] 2021-02-24 22:23
Seeing similar behaviour here on Android 11/Pixel 3 XL with 0.6.14. I had a couple of messages take minutes though, not seconds, to send and appear properly in the conversation.

Navigating away from the conversation, I could see part of the first message appear as a draft in the contact/conversation list. After some time this seemed to repeat for the second message I had sent as well. Perhaps sending two messages in quick succession was enough to really exacerbate whatever the underlying issue is.

**Comment by michaelkourlas** [comment] 2021-02-25 00:15
I'm actively investigating this.

**Comment by yulman19** [comment] 2021-02-27 02:15
same here with android 11 on a Pixel 3a

**Comment by hdlineage** [comment] 2021-02-27 05:43
Same problem here on LG V30 android 9

**Comment by kevinklaam** [comment] 2021-02-27 17:34
on s10e android 11, messages will send after couple seconds or it will never end up sending or messages double send after an 10+mins, using voipms web interface doesnt repro the issue

**Comment by michaelkourlas** [comment] 2021-02-27 20:34
I expect this to be fixed in the next release.

**Comment by michaelkourlas** [comment] 2021-02-28 20:04
Nope, not fixed yet.

**Comment by hdlineage** [comment] 2021-02-28 22:08
Upgraded to 0.6.18. Message sent will now appear instantly, however, prior messages sent by others will disappear unless you leave the conversation and re-enter again. Messages sent by yourself are still visible.

**Comment by michaelkourlas** [comment] 2021-03-01 05:12
With a large database, I can reproduce the delay between when the "send" button is pressed and when it appears in the list. I've reimplemented the database using Room, and I think this has reduced the delay somewhat. I'm not sure what else I can do.

> Upgraded to 0.6.18. Message sent will now appear instantly, however, prior messages sent by others will disappear unless you leave the conversation and re-enter again. Messages sent by yourself are still visible.

I can't reproduce this at all.

**Closed by michaelkourlas** 2021-03-01 05:12 UTC
Labels: app bug
