### ISSUE TITLE
Feature Request: Set as default messaging app. 

### ISSUE THREAD

**Issue by Tin-man-0** [michaelkourlas/voipms-sms-client#233] opened 2021-04-10 04:04 UTC
So I find myself using the voip.ms sms messaging app more often the the android default text messaging app and went to try and set the voip.ms one my default for realizability among other things. Voip.ms app gets kicked to the curb in anything the cell phone does from sleep to just being killed and until i happen to open the app back up again i won't see alot of notifications. I'm hoping by setting it as the default messaging app would fix that along with giving me just one place for all text messages.

**Comment by michaelkourlas** [comment] 2021-04-10 12:36
Duplicate of #49

**Closed by michaelkourlas** 2021-04-10 12:36 UTC
