### ISSUE TITLE
In notification pane error

### ISSUE THREAD

**Issue by Playdifferent** [michaelkourlas/voipms-sms-client#79] opened 2016-09-17 22:48 UTC
When I click on the new MSG, I am never brought to the conversation.  Nothing happens

**Comment by michaelkourlas** [comment] 2016-09-18 00:39
To clarify, when you click on a notification, you aren't taken to the conversation view?

**Comment by michaelkourlas** [comment] 2016-09-19 17:22
I'm going to close this as I can't reproduce this on 4.4, which is the version of Android you said you were running in another thread. Can you give me any more info?

**Closed** 2016-09-19 17:22 UTC
Labels: invalid
