### ISSUE TITLE
SMS Email Address

### ISSUE THREAD

**Issue by yuweikoo** [michaelkourlas/voipms-sms-client#47] opened 2016-01-15 20:10 UTC
After using the client, sms messages no longer are forwarded to email.  Under Manage DIDs, email address field is blank, eventhough email address was previously entered and enabled.

**Comment by michaelkourlas** [comment] 2016-01-16 00:11
This is a bug. I'll take a look.

**Comment by Grogdor** [comment] 2016-07-12 20:24
Confirmed, looks like automatically adding the URL callback blows away the email address.

**Comment by michaelkourlas** [comment] 2016-09-11 22:46
I've determined that this is a problem with the VoIP.ms API. When the app sets the URL callback using the `setSMS` API method, it doesn't set the email callback parameter. However, the API appears to disable all callbacks unless they are explicitly included in each invocation of the `setSMS` API method. This is just bad API design on VoIP.ms's part.

I suppose the app could get all of the enabled callbacks and include them in its request to set the URL callback, but it really shouldn't have to do this; moreover, if VoIP.ms decides to add a new parameter to the `setSMS` API method, the app will start resetting data again.

I'm going to close this issue since it isn't a problem with the app; however, I will ask them to fix this.

**Closed by michaelkourlas** 2016-09-11 22:46 UTC
Labels: bug
