### ISSUE TITLE
Messages taking a long time after I hit send

### ISSUE THREAD

**Issue by kevingatera** [michaelkourlas/voipms-sms-client#228] opened 2021-02-28 16:39 UTC
Hello, in the past few versions, the messages are taking a long taking a long time from the time I hit send to the time they show up as in the thread with the tag "sending". There's like 2 or 3 seconds where I am not sure where the message disappeared to. Thanks.

**Note:** I just saw that there was a similar bug marked as resolved but this issue is still partially present in 0.6.18. Although the messages still take about 2-3 seconds. Is there a way to get instantaneous appearance in the thread while it's sending?

**Comment by michaelkourlas** [comment] 2021-02-28 17:10
Duplicate of #227.

**Closed by michaelkourlas** 2021-02-28 17:10 UTC

**Comment by michaelkourlas** [comment] 2021-02-28 17:12
The messages are already added to the database immediately after you press "Send". The conversation is then refreshed right after. If there's a delay, it's probably a DB performance issue.

**Comment by michaelkourlas** [comment] 2021-02-28 17:13
FWIW, messages appear instantaneously on my Pixel 2 XL.
