### ISSUE TITLE
Cannot Synchronize

### ISSUE THREAD

**Issue by pstenson** [michaelkourlas/voipms-sms-client#125] opened 2017-06-21 12:25 UTC
"You have no messages". Refresh gives error message "Synchronization with VOIP.ms failed. The VOIP.ms API response could not be parsed".  Latest app version 0.5.2

**Comment by michaelkourlas** [comment] 2017-06-21 15:16
Try updating to 0.5.3 and tell me what the error message says then.

**Comment by michaelkourlas** [comment] 2017-06-27 20:12
This is probably a dupe of #126.

**Closed by michaelkourlas** 2017-06-27 20:12 UTC
