### ISSUE TITLE
Performance issue/hangs in 0.6.6

### ISSUE THREAD

**Issue by mang1ed** [michaelkourlas/voipms-sms-client#217] opened 2020-09-21 02:21 UTC
0.6.6 fdroid version appears to freeze and or would take long during sync and or when loading keyboard/minimising the app (having to force close the app). I tried to reinstall the app and clearing data/cache. App works fine for the first few messages and then starts to hang. I had to revert to 0.6.5 as this one works great on my device. I'm running /e/ on a note 3.

**Comment by michaelkourlas** [comment] 2020-09-21 03:22
I've gotten multiple reports of this and the common factor seems to be older versions of Android. (The app works fine on my own device -- Pixel 2 XL running Android 11.) Maybe the updated support libraries I'm using in the new build are buggy. I also started using WorkManager for the first time, since JobIntentService was deprecated.

Other than that, I don't know what the cause might be.

**Comment by mang1ed** [comment] 2020-09-21 17:59
My device is running android 7.1.2. There could be an incompatability with the libraries like you've mentioned.

**Comment by baldurmen** [comment] 2020-09-21 19:38
I have similar issues running the app on Android 9. Certainly not the latest version, but I wouldn't say it's "old" :)

**Comment by pcpumpkin** [comment] 2020-09-27 05:39
I am running Android 11 on Pixel 4a and having similar hanging/slow to load.

**Comment by LinearDynamics** [comment] 2020-09-28 16:50
Also experiencing this issue from the recent update. In Android settings>Battery>Advanced, Voip.ms SMS app used 21% since last full charge. UI doesn't load message threads.
Android 10, OnePlus 6t(Oxygen 10.3.5).
In the meantime, I'm using the not so great web page for my SMS https://voip.ms/m/communications.php

**Comment by michaelkourlas** [comment] 2020-09-28 16:52
Unfortunately, I'm at a loss. I'm just not experiencing these issues, so I don't know what's causing them.

**Comment by michaelkourlas** [comment] 2020-09-28 17:06
A user said that rebooting fixed the problem with the latest version. I wonder...

At first I thought this was happening because there were multiple OkHttp client instances. That probably didn't help, but it sounds like fixing that didn't fix the underlying problem, which is some kind of memory leak.

Based on [this StackOverflow question](https://stackoverflow.com/questions/56395158/getting-memory-leaks-with-okhttp), I think this is because I'm not closing the HTTP connection.

Will quickly release an update to fix this.

**Comment by michaelkourlas** [comment] 2020-09-28 17:10
Actually, never mind, I was already closing the response.

**Comment by michaelkourlas** [comment] 2020-09-28 17:11
@LinearDynamics -- what happens if you restart your device? Does the problem go away for you too?

**Comment by LinearDynamics** [comment] 2020-09-28 17:17
> @LinearDynamics -- what happens if you restart your device? Does the problem go away for you too?

Unfortunately, no. I did try that yesterday. Also today. Performed an uninstall/reinstall(with login to the API) but phone became noticeably hot after each test. In a bit I was going to try to delete the database, uninstall, set the synch start to August and retest. Not sure if that would be a worthwhile effort.
When initially starting the app, I can(sometimes) load the sms threads and reply however after a minute the unresponsiveness begins to occur.

**Comment by michaelkourlas** [comment] 2020-09-28 22:12
> In a bit I was going to try to delete the database, uninstall, set the synch start to August and retest. Not sure if that would be a worthwhile effort.

It might be. This might be a scaling issue.

**Comment by LinearDynamics** [comment] 2020-09-28 22:33
Ok, I set synch date to September 15,deleted dB, cleaned up.
In the past 10 minutes I'm able to send messages to my own DID. Works quickly and reliably.
My phone is not getting the heat blast like it was before. 
So for now, I'll keep the synch start as is and report back.

**Comment by yulman19** [comment] 2020-09-29 11:52
I'm not sure i'm in the good thread, but since last update i'm having a lot of troubles with the app similar to the ones mentionned with a fresh DB.
Android 11 on a Pixel 3a.

**Closed** 2020-09-29 13:58 UTC
Labels: app bug

**Comment by michaelkourlas** [comment] 2020-09-29 14:00
I'm just going to start using IntentService again. I don't care that it's deprecated -- the implementation is super straightforward. I'll just [make my own copy](https://github.com/michaelkourlas/voipms-sms-client/blob/master/voipms-sms/src/main/kotlin/net/kourlas/voipms_sms/utils/IntentService.kt) in case they ever remove it.

**Comment by AMDSeb** [comment] 2020-09-29 18:32
> I'm just going to start using IntentService again. I don't care that it's deprecated -- the implementation is super straightforward. I'll just [make my own copy](https://github.com/michaelkourlas/voipms-sms-client/blob/master/voipms-sms/src/main/kotlin/net/kourlas/voipms_sms/utils/IntentService.kt) in case they ever remove it.

Thanks a lot once again for your work. I was also experiencing very long waits when sending messages (1-2 minutes) since the last version update. Running Android 8 (annoying manufacturers, should be mandatory to keep updating for a certain period). I was about to post to see if I could help pinpoint the problem, but saw you had published a new version. Just tried it and it seems back to normal, no more hangs. Thanks again!

**Comment by michaelkourlas** [comment] 2020-09-29 18:48
That's great to hear! If 0.6.8 fixed things for anyone else -- or if the problem's still there -- please let me know.

**Comment by LinearDynamics** [comment] 2020-09-29 19:00
I extended my synch time back to 2018. All messages are present and performance seems normal.

**Comment by michaelkourlas** [comment] 2020-10-22 16:40
I think the problem here, for reference, was that I was using WorkManager incorrectly -- the work was running on the UI thread.
