### ISSUE TITLE
Display contact phone number in conversation

### ISSUE THREAD

**Issue by hackmyl1fe** [michaelkourlas/voipms-sms-client#68] opened 2016-07-30 19:06 UTC
It would be nice to have a way to tell to which phone number you are about to send your text to. 
If i have a contact with 2 phone numbers, it'd be nice to know which phone number is being used in a conversation.

For example, the phone number could be displayed in the "Send message" box in the conversation. This way we know what phone number is being used. (See [example](https://cloud.githubusercontent.com/assets/16405184/17272538/09d43d12-5667-11e6-837e-0ddcbf5352bd.png))

I'm not sure how hard that is to implement, but i'd be a nice feature

**Comment by michaelkourlas** [comment] 2016-08-13 00:18
This is a duplicate of issue #31.

**Closed by michaelkourlas** 2016-08-13 00:18 UTC
Labels: duplicate
