### ISSUE TITLE
Sync Notification is Annoying

### ISSUE THREAD

**Issue by michaelkuzmin** [michaelkourlas/voipms-sms-client#165] opened 2018-05-31 13:32 UTC
I lost my phone and had to buy the same device again. When I recovered I started to get push notifications from VoIP.ms SMS that synch is in progress. Not sure if it has something to do with the fact that I restored from backup or if that aspect is just a coincidence. In any event, I don't remember ever seeing these notifications before and now they come up regularly. The notification area is showing a message icon with arrows inside for a few seconds, then it disappears. Any idea why this started happening?

**Comment by michaelkourlas** [comment] 2018-05-31 13:37
Duplicate of #159.

**Closed by michaelkourlas** 2018-05-31 13:37 UTC
Labels: duplicate
