### ISSUE TITLE
Long SMS > 160 bytes are not concatenated

### ISSUE THREAD

**Issue by kaechele** [michaelkourlas/voipms-sms-client#230] opened 2021-03-29 16:39 UTC
Maybe a follow-up to #69, however when sending a long SMS through the voip.ms Webinterface it is correctly concatenated.

I used the following 400 byte text snippet for testing:
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur dolor velit, tempus a consectetur eu, mollis sed sapien. Curabitur eget dolor mi. Proin faucibus, tellus quis mattis aliquam, dui erat tincidunt nunc, vel malesuada odio nunc non ante. Phasellus convallis, mi in malesuada lacinia, ipsum diam egestas nulla, at pretium enim ante at eros. Suspendisse mollis magna erat, imperdiet eros. 
# View from within the voip.ms SMS app
![View from within the voip.ms SMS app](https://user-images.githubusercontent.com/454490/112869671-65efcb80-908b-11eb-86fa-38dc3100137e.jpg)

# Result from App on Android SMS
![Result from App on Android SMS app](https://user-images.githubusercontent.com/454490/112869339-0abdd900-908b-11eb-9062-31a4ee5a1425.jpg)

# View from voip.ms Webinterface
The last message sent was composed from within the webinterface.
![View from voip.ms Webinterface](https://user-images.githubusercontent.com/454490/112869751-7bfd8c00-908b-11eb-82a0-58819d43308f.jpg)

# Result from Webinterface on Android SMS
![Result from Webinterface on Android SMS](https://user-images.githubusercontent.com/454490/112869819-92a3e300-908b-11eb-8469-e4ef5be13368.jpg)

**Comment by kaechele** [comment] 2021-03-29 16:46
This is the form data that is being sent from the webinterface when sending a long SMS:
```json
{
	"method": "send_message",
	"contact": "416xxxxxxx",
	"did": "647478xxxx",
	"typemsg": "MMS",
	"msg": "Lorem+ipsum+dolor+sit+amet,+consectetur+adipiscing+elit.+Curabitur+dolor+velit,+tempus+a+consectetur+eu,+mollis+sed+sapien.+Curabitur+eget+dolor+mi.+Proin+faucibus,+tellus+quis+mattis+aliquam,+dui+erat+tincidunt+nunc,+vel+malesuada+odio+nunc+non+ante.+Phasellus+convallis,+mi+in+malesuada+lacinia,+ipsum+diam+egestas+nulla,+at+pretium+enim+ante+at+eros.+Suspendisse+mollis+magna+erat,+imperdiet+eros.",
	"media1": "",
	"media1type": "",
	"media1realtype": "",
	"media2": "",
	"media2type": "",
	"media2realtype": "",
	"media3": "",
	"media3type": "",
	"media3realtype": ""
}
```
Note how `typemsg` is `MMS`.

For comparison a message that is exactly 160 bytes:
```json
{
	"method": "send_message",
	"contact": "416xxxxxxx",
	"did": "647478xxx",
	"typemsg": "SMS",
	"msg": "Lorem+ipsum+dolor+sit+amet,+consectetur+adipiscing+elit.+Proin+leo+ante,+aliquet+sed+viverra+eu,+tristique+non+orci.+Proin+neque+dui,+hendrerit+nec+massa+proin.",
	"media1": "",
	"media1type": "",
	"media1realtype": "",
	"media2": "",
	"media2type": "",
	"media2realtype": "",
	"media3": "",
	"media3type": "",
	"media3realtype": ""
}
```
Here `typemsg` is `SMS`.

**Comment by kaechele** [comment] 2021-03-29 16:50
To send MMS from the API the `sendMMS` endpoint must be used. So this is related to #190.

**Comment by michaelkourlas** [comment] 2021-03-29 19:09
Correct, this is a duplicate of #190.

**Closed by michaelkourlas** 2021-03-29 19:09 UTC
